name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"  # Trigger only on version tags
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build tools (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install mingw -y
        shell: cmd

      - name: Install dependencies (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: |
          if [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then sudo apt-get install -y build-essential cmake; fi
          if [[ ${{ matrix.os }} == "macos-latest" ]]; then brew install --formula cmake; fi

      - name: Configure with CMake
        run: |
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then cmake -G "MinGW Makefiles" -S . -B build; fi
          if [[ ${{ matrix.os }} != "windows-latest" ]]; then cmake -S . -B build; fi
          cmake --build build --config Release

      - name: Archive Build Artifacts
        run: |
          mkdir -p dist
          if [[ ${{ matrix.os }} == "ubuntu-latest" ]]; then tar -czvf dist/linux-build.tar.gz build/; fi
          if [[ ${{ matrix.os }} == "macos-latest" ]]; then tar -czvf dist/mac-build.tar.gz build/; fi
          if [[ ${{ matrix.os }} == "windows-latest" ]]; then 7z a dist/windows-build.zip build/*; fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-build
          path: dist/
